---
- name: 'install packages'
  apt:
    name: '{{mirror_pkgs}}'
    state: present
  become: true
  tags:
  - ct-aptmirror
  - ct-aptmirror-pkg

- name: 'sort out directories'
  file:
    mode: '{{item.mode}}'
    path: '{{item.path}}'
    state: directory
  loop: '{{mirror_dirs}}'
  become: true
  tags:
  - ct-aptmirror

- name: 'prepare mirror list'
  template:
    src: mirror.list.j2
    dest: '/etc/apt/mirror.list'
    mode: '0644'
  become: true
  tags:
  - ct-aptmirror

- name: 'copy postmirror script over'
  copy:
    src: postmirror.sh
    dest: '{{mirror_base}}/var/postmirror.sh'
    mode: '0744'
  become: true
  tags:
  - ct-aptmirror

- name: 'cron job for weekly clean up'
  cron:
    name: 'apt-mirror-clean-weekly'
    state: present
    disabled: false
    user: root
    minute: '05'
    hour: '22'
    job: '{{mirror_base}}/var/clean.sh'
    weekday: '{{mirror_cron_day_clean}}'
  become: true
  tags:
  - ct-aptmirror
  - ct-aptmirror-cron

- name: 'schedule weekly updates by cron'
  cron:
    name: 'apt-mirror-weekly'
    state: present
    disabled: false
    user: root
    minute: '05'
    hour: '02'
    job: /usr/bin/apt-mirror
    weekday: '{{mirror_cron_day_refresh}}'
  become: true
  tags:
  - ct-aptmirror
  - ct-aptmirror-cron
...
